{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Task overview:\n",
    "\n",
    "\n",
    "Liquidity Risk:  The task centers around predicting the cost of selling a security. In Asset Management, we always need to ensure that the portfolio has enough liquidity such that, should we have to sell a large amount of assets, not too large a cost would be incurred. \n",
    "\n",
    "So we have function $C = F(v,t)$ where \n",
    "* $v =$ volume ($x10^8$ \\$M)\n",
    "* $t =$ time horizon (days)\n",
    "* $C =$ Liquidation Cost (%)\n",
    "\n",
    "where liquidation cost here is the percentage cost of liquidating an asset based on time, volume (and other exogenous market factors)\n",
    "\n",
    "More precisely we are given:\n",
    "$$C = \\alpha +  \\begin{bmatrix}\n",
    "    \\beta_1 \\\\\n",
    "    \\beta_2\n",
    "  \\end{bmatrix} \\cdot \\begin{bmatrix} v \\; \\; t \\end{bmatrix} + \\epsilon $$\n",
    "\n",
    "\n",
    "#### Rapid Fire Thoughts\n",
    "1. First determine what the cost column is in the mins and hours data\n",
    "1. Check for erroneous data\n",
    "1. Correlation plots to see if any clear patterns between volume/time features and cost\n",
    "1. Check for collinearity \n",
    "1. Possibly automated time series feature extraction with TS Fresh\n",
    "1. For simplicity structure this as supervised learning problem with lag i.e. where $x$ is row in X which is an $n\\times m$ matrix with $x = [a_1, a_2, a_3, \\dots b_2, b_3]$ and $\\hat{y}=[t_5]$  \n",
    "1. Quickly reference some research papers for possible signals i.e. lags, sin/cos on time etc."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pandas_profiling import ProfileReport\n",
    "import etl \n",
    "ticker_df, lob_df = etl.get_data()\n",
    "ticker_profile = ProfileReport(ticker_df, title=\"Pandas Profiling Report - Minutes Data\")\n",
    "lob_profile = ProfileReport(lob_df, title=\"Pandas Profiling Report - Hours Data\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "bids, asks = denorm_order_book(limit_order_book_df,\"Bid\"), denorm_order_book(limit_order_book_df,\"Ask\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "average_asks = asks.groupby([\"Price\"]).mean().reset_index()\n",
    "average_asks = average_asks.add_prefix(\"Average_\")\n",
    "\n",
    "average_bids = bids.groupby([\"Price\"]).mean().reset_index()\n",
    "average_bids = average_bids.add_prefix(\"Average_\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f0ff60d03be8448c8e781106e4623841",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(FloatProgress(value=0.0, description='Summarize dataset', max=28.0, style=ProgressStyle(descripâ€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-80c6524d9691>\", line 1, in <module>\n",
      "    ticker_profile\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/displayhook.py\", line 262, in __call__\n",
      "    format_dict, md_dict = self.compute_format_data(result)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/displayhook.py\", line 151, in compute_format_data\n",
      "    return self.shell.display_formatter.format(result)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 180, in format\n",
      "    data = formatter(obj)\n",
      "  File \"<decorator-gen-9>\", line 2, in __call__\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 224, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 345, in __call__\n",
      "    return method()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 397, in _repr_html_\n",
      "    self.to_notebook_iframe()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 377, in to_notebook_iframe\n",
      "    display(get_notebook_iframe(self))\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/report/presentation/flavours/widget/notebook.py\", line 65, in get_notebook_iframe\n",
      "    output = get_notebook_iframe_srcdoc(profile)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/report/presentation/flavours/widget/notebook.py\", line 23, in get_notebook_iframe_srcdoc\n",
      "    src = html.escape(profile.to_html())\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 348, in to_html\n",
      "    return self.html\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 168, in html\n",
      "    self._html = self._render_html()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 275, in _render_html\n",
      "    report = self.report\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 162, in report\n",
      "    self._report = get_report_structure(self.description_set)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 143, in description_set\n",
      "    self._description_set = describe_df(self.title, self.df)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/model/describe.py\", line 93, in describe\n",
      "    scatter_matrix = get_scatter_matrix(df, variables)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/model/summary.py\", line 668, in get_scatter_matrix\n",
      "    scatter_matrix[x][y] = scatter_pairwise(df[x], df[y], x, y)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/visualisation/plot.py\", line 264, in scatter_pairwise\n",
      "    return plot_360_n0sc0pe(plt)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/visualisation/utils.py\", line 68, in plot_360_n0sc0pe\n",
      "    plt.savefig(image_str, format=image_format)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/pyplot.py\", line 843, in savefig\n",
      "    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/image.py\", line 132, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py\", line 2708, in draw\n",
      "    self._update_title_position(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py\", line 2644, in _update_title_position\n",
      "    bb = ax.xaxis.get_tightbbox(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 1111, in get_tightbbox\n",
      "    self._update_label_position(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 2058, in _update_label_position\n",
      "    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 2042, in _get_tick_boxes_siblings\n",
      "    ticks_to_draw = axx.xaxis._update_ticks()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 1022, in _update_ticks\n",
      "    major_labels = self.major.formatter.format_ticks(major_locs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 249, in format_ticks\n",
      "    self.set_locs(values)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 780, in set_locs\n",
      "    self._compute_offset()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 793, in _compute_offset\n",
      "    lmin, lmax = locs.min(), locs.max()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/numpy/core/_methods.py\", line 39, in _amax\n",
      "    return umr_maximum(a, axis, None, out, keepdims, initial, where)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 721, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/posixpath.py\", line 381, in abspath\n",
      "    return normpath(path)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/posixpath.py\", line 358, in normpath\n",
      "    if comp in (empty, dot):\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-80c6524d9691>\", line 1, in <module>\n",
      "    ticker_profile\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/displayhook.py\", line 262, in __call__\n",
      "    format_dict, md_dict = self.compute_format_data(result)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/displayhook.py\", line 151, in compute_format_data\n",
      "    return self.shell.display_formatter.format(result)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 180, in format\n",
      "    data = formatter(obj)\n",
      "  File \"<decorator-gen-9>\", line 2, in __call__\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 224, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 345, in __call__\n",
      "    return method()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 397, in _repr_html_\n",
      "    self.to_notebook_iframe()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 377, in to_notebook_iframe\n",
      "    display(get_notebook_iframe(self))\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/report/presentation/flavours/widget/notebook.py\", line 65, in get_notebook_iframe\n",
      "    output = get_notebook_iframe_srcdoc(profile)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/report/presentation/flavours/widget/notebook.py\", line 23, in get_notebook_iframe_srcdoc\n",
      "    src = html.escape(profile.to_html())\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 348, in to_html\n",
      "    return self.html\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 168, in html\n",
      "    self._html = self._render_html()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 275, in _render_html\n",
      "    report = self.report\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 162, in report\n",
      "    self._report = get_report_structure(self.description_set)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 143, in description_set\n",
      "    self._description_set = describe_df(self.title, self.df)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/model/describe.py\", line 93, in describe\n",
      "    scatter_matrix = get_scatter_matrix(df, variables)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/model/summary.py\", line 668, in get_scatter_matrix\n",
      "    scatter_matrix[x][y] = scatter_pairwise(df[x], df[y], x, y)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/visualisation/plot.py\", line 264, in scatter_pairwise\n",
      "    return plot_360_n0sc0pe(plt)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/visualisation/utils.py\", line 68, in plot_360_n0sc0pe\n",
      "    plt.savefig(image_str, format=image_format)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/pyplot.py\", line 843, in savefig\n",
      "    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/image.py\", line 132, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py\", line 2708, in draw\n",
      "    self._update_title_position(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py\", line 2644, in _update_title_position\n",
      "    bb = ax.xaxis.get_tightbbox(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 1111, in get_tightbbox\n",
      "    self._update_label_position(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 2058, in _update_label_position\n",
      "    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 2042, in _get_tick_boxes_siblings\n",
      "    ticks_to_draw = axx.xaxis._update_ticks()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 1022, in _update_ticks\n",
      "    major_labels = self.major.formatter.format_ticks(major_locs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 249, in format_ticks\n",
      "    self.set_locs(values)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 780, in set_locs\n",
      "    self._compute_offset()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 793, in _compute_offset\n",
      "    lmin, lmax = locs.min(), locs.max()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/numpy/core/_methods.py\", line 39, in _amax\n",
      "    return umr_maximum(a, axis, None, out, keepdims, initial, where)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 744, in getmodule\n",
      "    for modname, module in sys.modules.copy().items():\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3417, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-80c6524d9691>\", line 1, in <module>\n",
      "    ticker_profile\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/displayhook.py\", line 262, in __call__\n",
      "    format_dict, md_dict = self.compute_format_data(result)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/displayhook.py\", line 151, in compute_format_data\n",
      "    return self.shell.display_formatter.format(result)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 180, in format\n",
      "    data = formatter(obj)\n",
      "  File \"<decorator-gen-9>\", line 2, in __call__\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 224, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/formatters.py\", line 345, in __call__\n",
      "    return method()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 397, in _repr_html_\n",
      "    self.to_notebook_iframe()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 377, in to_notebook_iframe\n",
      "    display(get_notebook_iframe(self))\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/report/presentation/flavours/widget/notebook.py\", line 65, in get_notebook_iframe\n",
      "    output = get_notebook_iframe_srcdoc(profile)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/report/presentation/flavours/widget/notebook.py\", line 23, in get_notebook_iframe_srcdoc\n",
      "    src = html.escape(profile.to_html())\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 348, in to_html\n",
      "    return self.html\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 168, in html\n",
      "    self._html = self._render_html()\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 275, in _render_html\n",
      "    report = self.report\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 162, in report\n",
      "    self._report = get_report_structure(self.description_set)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/profile_report.py\", line 143, in description_set\n",
      "    self._description_set = describe_df(self.title, self.df)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/model/describe.py\", line 93, in describe\n",
      "    scatter_matrix = get_scatter_matrix(df, variables)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/model/summary.py\", line 668, in get_scatter_matrix\n",
      "    scatter_matrix[x][y] = scatter_pairwise(df[x], df[y], x, y)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/visualisation/plot.py\", line 264, in scatter_pairwise\n",
      "    return plot_360_n0sc0pe(plt)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/site-packages/pandas_profiling/visualisation/utils.py\", line 68, in plot_360_n0sc0pe\n",
      "    plt.savefig(image_str, format=image_format)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/pyplot.py\", line 843, in savefig\n",
      "    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/image.py\", line 132, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py\", line 2708, in draw\n",
      "    self._update_title_position(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py\", line 2644, in _update_title_position\n",
      "    bb = ax.xaxis.get_tightbbox(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 1111, in get_tightbbox\n",
      "    self._update_label_position(renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 2058, in _update_label_position\n",
      "    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 2042, in _get_tick_boxes_siblings\n",
      "    ticks_to_draw = axx.xaxis._update_ticks()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/axis.py\", line 1022, in _update_ticks\n",
      "    major_labels = self.major.formatter.format_ticks(major_locs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 249, in format_ticks\n",
      "    self.set_locs(values)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 780, in set_locs\n",
      "    self._compute_offset()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/matplotlib/ticker.py\", line 793, in _compute_offset\n",
      "    lmin, lmax = locs.min(), locs.max()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/numpy/core/_methods.py\", line 39, in _amax\n",
      "    return umr_maximum(a, axis, None, out, keepdims, initial, where)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3337, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3434, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1192, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2922, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3145, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3356, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2046, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1335, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1210, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/philip/.local/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/posixpath.py\", line 391, in realpath\n",
      "    path, ok = _joinrealpath(filename[:0], filename, {})\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/posixpath.py\", line 425, in _joinrealpath\n",
      "    if not islink(newpath):\n",
      "  File \"/home/philip/miniconda3/envs/gam_test/lib/python3.8/posixpath.py\", line 167, in islink\n",
      "    st = os.lstat(path)\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "ticker_profile"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "lob_profile"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
